Repository JonathanSalwan/Triton, pull requests merged in 2020-02, with the labels that each got.

#847 Update dependency versions in Dockerfile
  Dockerfile
Labels: Compile, Enhancement

#848 Fix taint propagation in PXOR
  src/libtriton/arch/x86/x86Semantics.cpp
Labels: Enhancement, Taint Engine, libTriton

#854 Update Appveyor VS19 and support python 3
  .appveyor.yml
Labels: Compile, Enhancement, Windows, libTriton
