Repository JonathanSalwan/Triton, pull requests merged in 2022-11, with the labels that each got.

#1200 Store instruction address in symbolic expression created from instructions.
  src/libtriton/engines/symbolic/symbolicEngine.cpp
  src/libtriton/engines/symbolic/symbolicExpression.cpp
  src/libtriton/includes/triton/symbolicExpression.hpp
Labels: Enhancement, Core, libTriton

#1209 Check if PYTHON_SITE_PACKAGES is defined
  doc/CMakeLists.txt
  src/libtriton/CMakeLists.txt
Labels: Enhancement, Compile

#1213 Update example.py
  doc/autocomplete/example.py
Labels: Bug, Documentation
