Repository JonathanSalwan/Triton, pull requests merged in 2022-06, with the labels that each got.

#1134 Support instruction assembly printing for symbolic expressions in lifting engine
  src/libtriton/api/api.cpp
  src/libtriton/bindings/python/objects/pyTritonContext.cpp
  src/libtriton/engines/lifters/liftingToPython.cpp
  src/libtriton/engines/lifters/liftingToSMT.cpp
  src/libtriton/includes/triton/api.hpp
  src/libtriton/includes/triton/liftingToPython.hpp
  src/libtriton/includes/triton/liftingToSMT.hpp
Labels: Feature, libTriton, AST Lifting

#1138 prevent apple m1 defaulting dockerfile to arm64 by specifying intent for amd64 + more appveyor python windows binary versions
  Dockerfile
Labels: External tool, libTriton, Compile

#1140 more appveyor python versions?
  .appveyor.yml
Labels: External tool, libTriton, Compile

#1142 Fix compilation issues with python 3.12
  src/libtriton/bindings/python/utils.cpp
  src/libtriton/includes/triton/pythonBindings.hpp
Labels: Enhancement, libTriton, Compile

#1147 #1145: Add support for Linux and Bitwuzla
  .github/workflows/python.yml
Labels: Enhancement, libTriton, Compile
