Repository JonathanSalwan/Triton, pull requests merged in 2024-10, with the labels that each got.

#1365 Fix bitwuzla not found on macos
  CMakeModules/FindBITWUZLA.cmake
Labels: Bug, Compile

#1368 Fix unsupported instruction for some bics variant
  src/libtriton/arch/arm/aarch64/aarch64Specifications.cpp
  src/testers/aarch64/unicorn_test_aarch64.py
Labels: Enhancement, ISA Semantics, libTriton

#1370 Fix Python workflow
  .github/workflows/python.yml
Labels: Enhancement, Compile

#1371 Update CI workflows
  .github/workflows/codecov.yml
  .github/workflows/docker.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/vcpkg.yml
Labels: Enhancement, Compile
